# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-11 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Owner',
            new_name='owner',
        ),
    ]
